-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Produto (
IDProduto SMALLINT PRIMARY KEY,
Nome VARCHAR(100),
Preco DOUBLE
);

CREATE TABLE Pedido (
IDProduto SMALLINT,
IDVenda SMALLINT,
Quantidade INTEGER,
FOREIGN KEY(IDProduto) REFERENCES Produto (IDProduto) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE Venda (
IDVenda SMALLINT PRIMARY KEY
);

ALTER TABLE Pedido ADD FOREIGN KEY(IDVenda) REFERENCES Venda (IDVenda) ON UPDATE RESTRICT ON DELETE RESTRICT;
