/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */
public class InterfacePrincipal extends FormTemplate {

    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bRealizarVenda = new javax.swing.JButton();
        lPanificadora = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuCadastrarPao = new javax.swing.JMenuItem();
        jMenuCadastroCliente = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuConsultarPaes = new javax.swing.JMenuItem();
        jMenuGerarRelatorio = new javax.swing.JMenu();
        jMenuGerarRelatorioCompraCliente = new javax.swing.JMenuItem();
        jMenuRelatorioVendaProduto = new javax.swing.JMenuItem();
        jMenuGerarRelatorioTotalRecebido = new javax.swing.JMenuItem();
        jMenuOpcao = new javax.swing.JMenu();
        jMenuOpcoesSair = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bRealizarVenda.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bRealizarVenda.setText("Realizar Venda");
        bRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarVendaActionPerformed(evt);
            }
        });

        lPanificadora.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lPanificadora.setText("Panificadora");

        jMenuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/add.png"))); // NOI18N
        jMenuCadastrar.setText("Cadastrar");
        jMenuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarActionPerformed(evt);
            }
        });

        jMenuCadastrarPao.setText("Pão");
        jMenuCadastrarPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarPaoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastrarPao);

        jMenuCadastroCliente.setText("Cliente");
        jMenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClienteActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastroCliente);

        jMenu.add(jMenuCadastrar);

        jMenuConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lupa.png"))); // NOI18N
        jMenuConsultar.setText("Consultar");

        jMenuConsultarPaes.setText("Pães");
        jMenuConsultarPaes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarPaesActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuConsultarPaes);

        jMenu.add(jMenuConsultar);

        jMenuGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/door_out.png"))); // NOI18N
        jMenuGerarRelatorio.setText("Gerar Relatório");

        jMenuGerarRelatorioCompraCliente.setText("Compra Cliente");
        jMenuGerarRelatorioCompraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerarRelatorioCompraClienteActionPerformed(evt);
            }
        });
        jMenuGerarRelatorio.add(jMenuGerarRelatorioCompraCliente);

        jMenuRelatorioVendaProduto.setText("Venda Produto");
        jMenuRelatorioVendaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioVendaProdutoActionPerformed(evt);
            }
        });
        jMenuGerarRelatorio.add(jMenuRelatorioVendaProduto);

        jMenuGerarRelatorioTotalRecebido.setText("Total Recebido");
        jMenuGerarRelatorioTotalRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerarRelatorioTotalRecebidoActionPerformed(evt);
            }
        });
        jMenuGerarRelatorio.add(jMenuGerarRelatorioTotalRecebido);

        jMenu.add(jMenuGerarRelatorio);

        jMenuOpcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/config.png"))); // NOI18N
        jMenuOpcao.setText("Opções");

        jMenuOpcoesSair.setText("Sair");
        jMenuOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpcoesSairActionPerformed(evt);
            }
        });
        jMenuOpcao.add(jMenuOpcoesSair);

        jMenu.add(jMenuOpcao);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lPanificadora)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lPanificadora)
                .addGap(44, 44, 44)
                .addComponent(bRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarVendaActionPerformed
        VendaPao venda = new VendaPao();
        venda.setLocationRelativeTo(null);
        venda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRealizarVendaActionPerformed

    private void jMenuCadastrarPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarPaoActionPerformed
        
        CadastroProduto cadastroProduto = new CadastroProduto();
        cadastroProduto.setLocationRelativeTo(null);
        cadastroProduto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuCadastrarPaoActionPerformed

    private void jMenuConsultarPaesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarPaesActionPerformed
        ConsultarProduto consultarProduto = new ConsultarProduto();
        consultarProduto.setLocationRelativeTo(null);
        consultarProduto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuConsultarPaesActionPerformed

    private void jMenuOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpcoesSairActionPerformed
        JOptionPane.showMessageDialog(this, "Saindo do Sistema", "Alerta do Sistema", JOptionPane.WARNING_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jMenuOpcoesSairActionPerformed

    private void jMenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClienteActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setLocationRelativeTo(null);
        cadastroCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuCadastroClienteActionPerformed

    private void jMenuRelatorioVendaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioVendaProdutoActionPerformed
        RelatorioVendaProduto relatorioVendaProduto = new RelatorioVendaProduto();
        relatorioVendaProduto.setLocationRelativeTo(null);
        relatorioVendaProduto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuRelatorioVendaProdutoActionPerformed

    private void jMenuGerarRelatorioCompraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerarRelatorioCompraClienteActionPerformed
        RelatorioCompraCliente relatorioCompraCliente = new RelatorioCompraCliente();
        relatorioCompraCliente.setLocationRelativeTo(null);
        relatorioCompraCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuGerarRelatorioCompraClienteActionPerformed

    private void jMenuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastrarActionPerformed

    private void jMenuGerarRelatorioTotalRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerarRelatorioTotalRecebidoActionPerformed
        RelatorioTotalRecebido relatorioTotalRecebido = new RelatorioTotalRecebido();
        relatorioTotalRecebido.setLocationRelativeTo(null);
        relatorioTotalRecebido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuGerarRelatorioTotalRecebidoActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRealizarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuCadastrarPao;
    private javax.swing.JMenuItem jMenuCadastroCliente;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuConsultarPaes;
    private javax.swing.JMenu jMenuGerarRelatorio;
    private javax.swing.JMenuItem jMenuGerarRelatorioCompraCliente;
    private javax.swing.JMenuItem jMenuGerarRelatorioTotalRecebido;
    private javax.swing.JMenu jMenuOpcao;
    private javax.swing.JMenuItem jMenuOpcoesSair;
    private javax.swing.JMenuItem jMenuRelatorioVendaProduto;
    private javax.swing.JLabel lPanificadora;
    // End of variables declaration//GEN-END:variables
    @Override
    public void bSobreActionPerformed(java.awt.event.ActionEvent evt) {                                       

        InterfacePrincipal interfacePrincipal = new InterfacePrincipal();
        interfacePrincipal.setLocationRelativeTo(null);
        interfacePrincipal.setVisible(true);
        this.dispose();
    }
}
