/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */
public class InterfacePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bRealizarVenda = new javax.swing.JButton();
        bRelatorios = new javax.swing.JButton();
        lPanificadora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuCadastrarPao = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuConsultarPaes = new javax.swing.JMenuItem();
        jMenuOpcao = new javax.swing.JMenu();
        jMenuOpcoesSair = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bRealizarVenda.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bRealizarVenda.setText("Realizar Venda");
        bRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarVendaActionPerformed(evt);
            }
        });

        bRelatorios.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bRelatorios.setText("Gerar Relatório");
        bRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRelatoriosActionPerformed(evt);
            }
        });

        lPanificadora.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lPanificadora.setText("Panificadora");

        jMenuCadastrar.setText("Cadastrar");

        jMenuCadastrarPao.setText("Pão");
        jMenuCadastrarPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarPaoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastrarPao);

        jMenuBar1.add(jMenuCadastrar);

        jMenuConsultar.setText("Consultar");

        jMenuConsultarPaes.setText("Pães");
        jMenuConsultarPaes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarPaesActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuConsultarPaes);

        jMenuBar1.add(jMenuConsultar);

        jMenuOpcao.setText("Opções");

        jMenuOpcoesSair.setText("Sair");
        jMenuOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpcoesSairActionPerformed(evt);
            }
        });
        jMenuOpcao.add(jMenuOpcoesSair);

        jMenuBar1.add(jMenuOpcao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRelatorios))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lPanificadora)
                .addGap(69, 69, 69))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bRealizarVenda, bRelatorios});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPanificadora)
                .addGap(59, 59, 59)
                .addComponent(bRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bRelatorios)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bRealizarVenda, bRelatorios});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarVendaActionPerformed
        VendaPao venda = new VendaPao();
        venda.setLocationRelativeTo(null);
        venda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRealizarVendaActionPerformed

    private void bRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRelatoriosActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.setLocationRelativeTo(null);
        relatorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bRelatoriosActionPerformed

    private void jMenuCadastrarPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarPaoActionPerformed
        CadastroPao cadastroPao = new CadastroPao();
        cadastroPao.setLocationRelativeTo(null);
        cadastroPao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuCadastrarPaoActionPerformed

    private void jMenuConsultarPaesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarPaesActionPerformed
        ConsultarProduto consultarProduto = new ConsultarProduto();
        consultarProduto.setLocationRelativeTo(null);
        consultarProduto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuConsultarPaesActionPerformed

    private void jMenuOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpcoesSairActionPerformed
        JOptionPane.showMessageDialog(this, "Saindo do Sistema", "Alerta do Sistema", JOptionPane.WARNING_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jMenuOpcoesSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRealizarVenda;
    private javax.swing.JButton bRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuCadastrarPao;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuConsultarPaes;
    private javax.swing.JMenu jMenuOpcao;
    private javax.swing.JMenuItem jMenuOpcoesSair;
    private javax.swing.JLabel lPanificadora;
    // End of variables declaration//GEN-END:variables
}
